---
branches: ["main"]
preset: "angular"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/github"

verifyConditions:
  - "@semantic-release/github"
analyzeCommits:
  - path: "@semantic-release/commit-analyzer"
    releaseRules:
      - type: "feat"
        release: "minor"
      - type: "hotfix"
        release: "patch"
      - type: "patch"
        release: "patch"
      - type: "minor"
        release: "minor"
      - type: "breaking"
        release: "major"

release:
  branches:
    - main

publish:
  - path: "@semantic-release/github"

success:
  - "@semantic-release/github"

fail:
  - "@semantic-release/github"
